server:
  port: 8080

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/my_bag
    driver-class-name: org.mariadb.jdbc.Driver
    username: user01
    password: user01
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    show-sql: true
    hibernate:
      ddl-auto: create
